services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=la vida es bella pero sin ella

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
        - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8989:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  postgres-volume:
