services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
        - postgres-volume:/var/lib/posgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8989:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  postgres-volume:
